CRITIC:
  model: ERNIE-4.0-8K-Latest
  max_retry: 4

SUMMARY:
  model: ERNIE-4.0-8K-Latest

SOLVER:
  model: ERNIE-Functions-8K
  total_retry: 12
  api_retry: 3

API_HELPER:
  model: ERNIE-3.5-8K #
  max_retry: 2

RETRIEVER_CRITIC:
  model: ERNIE-4.0-8K-Latest